AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SubnetId:
    Type: 'AWS::EC2::Subnet::Id'
  KeyName:
    Type: 'String'
    Description: 'Name of an existing EC2 KeyPair to enable SSH access to the instance'
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-05576a079321f21f8'
      KeyName: 'my-KeyPair-v2'
      SubnetId: !ImportValue MySubnetId
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install apache2 -y
          sudo systemctl start apache2
          sudo bash -c 'echo your very first web server > /var/www/html/index.html'
      SecurityGroupIds:
        - EC2SecurityGroup
      Tags:
        - Key: 'Name'
          Value: 'MyWebServerInstance'

  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable SSH and HTTP access'
      VpcId: !ImportValue MyVPCId
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: 'tcp'
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'
